pipeline:
  start_date: "2024-06"
  end_date: "2024-06"

bigquery:
  bronze_dataset: nyc_taxi_bronze

taxi_zones:
  source_path: data/taxi_zones/taxi_zones.shp
  target_crs: EPSG:4326
  table_name: taxi_zones