
name: 'nyc_yellow_taxi'
version: '1.0.0'

profile: 'nyc_yellow_taxi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  nyc_yellow_taxi:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table

seeds:
  nyc_yellow_taxi:
    +schema: seeds

vars:
  silver:
    mta_tax_max: 0.5
    improvement_surcharge_max: 5
    congestion_surcharge_max: 2.5
    airport_fee_max: 1.75 
    trip_duration_max: 120
  gold:
    trip_distance:
      short_max: 2.25
      medium_max: 5.3
      long_max: 10.05 
    tip_amount:
      low_max: 1
      medium_max: 3.30
      high_max: 8.68 
    total_amount:
      low_max: 15.6
      medium_max: 29.05
      high_max: 53.24 

